# Generated by Django 4.0.4 on 2022-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_admin_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='n_habitacion',
            field=models.IntegerField(unique=True, verbose_name='N° Habitación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='n_piso',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='N° Piso'),
        ),
    ]
