# Generated by Django 4.0.4 on 2022-05-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_cliente_estado_alter_habitacion_n_habitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='User Email'),
        ),
    ]
