# Generated by Django 4.0.4 on 2022-05-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_admin_correo_alter_cliente_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrador',
        ),
    ]
