# Generated by Django 4.0.4 on 2022-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_rename_admin_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Tarjeta de Debito', 'Tarjeta de Debito'), ('Tarjeta de credito', 'Tarjeta de Credito')], max_length=100)),
                ('total', models.IntegerField()),
                ('fec_salida', models.DateTimeField(verbose_name='fecha salida')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_entrada', models.DateTimeField(verbose_name='fecha entrada')),
                ('fec_salida', models.DateTimeField(verbose_name='fecha salida')),
                ('cant_personas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='n_habitacion',
            field=models.IntegerField(unique=True),
        ),
    ]
